[WIP] configure implementations with service ids
broadway/broadway-bundle pull request #19
Opened 2017-02-24 10:40 UTC by othillo

- [ ] configure event store with service id
- [ ] configure read model repository factory with service id
- [ ] configure saga state repository with service id

- [ ] merge https://github.com/broadway/broadway/pull/295
- [ ] merge https://github.com/broadway/broadway/pull/294
- [ ] merge https://github.com/broadway/event-store-dbal/pull/1
- [ ] merge https://github.com/broadway/read-model-elasticsearch/pull/1
- [ ] document how to use Doctrine DBAL
- [ ] document how to use Elasticsearch
- [ ] document how to use MongoDB
- [ ] update broadway/broadway-demo
- [ ] tag new release

2017-02-26 21:49 UTC, wjzijderveld requested changes

2017-02-26 21:49 UTC, wjzijderveld commented on README.md
> +You need to configure this event store in you application:
`You will need to configure an event store in your application's service definition`?

2017-02-26 21:49 UTC, wjzijderveld commented on test/AppKernel.php
> +        // TODO: Implement registerContainerConfiguration() method.
Remove todo (or actually do it 😋)

2017-02-26 21:49 UTC, wjzijderveld commented on README.md
> +broadway:
Add `# config.yml` on the first line to provide some context

2017-02-26 21:49 UTC, wjzijderveld commented on README.md
> +broadway:
This goes for all configuration code-blocks.

For the service definitions I think it's already obvious enough, but it doesn't hurt adding `<!-- services.xml -->` there as well.

2017-03-07 10:52 UTC, asm89 commented
@wjzijderveld @robinvdvleuten @ricbra Any objections? If none I'll merge this in the next couple of days.

2017-03-07 10:57 UTC, robinvdvleuten commented
@asm89 looks very good to me! Nice work @othillo 👍

2017-06-02 20:24 UTC, wjzijderveld approved these changes

2017-07-08 13:14 UTC, merged

2017-07-08 13:14 UTC, wjzijderveld commented
Thanks @othillo !

2017-07-08 17:03 UTC, othillo commented
@wjzijderveld time to tag 1.0? or just 0.3?